[package]
name = "erdgen"
version = "0.1.0"
edition = "2024"

[dependencies]
graphviz-rust = "0.9.3"
indexmap = { version = "2.8.0", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde-hjson = "1.1.0"
