use serde::{Deserialize, Serialize};

#[derive(Debug, Default, Deserialize, Serialize, Clone, Copy, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum Color {
    AliceBlue,
    AntiqueWhite,
    AntiqueWhite1,
    AntiqueWhite2,
    AntiqueWhite3,
    AntiqueWhite4,
    Aqua,
    Aquamarine,
    Aquamarine1,
    Aquamarine2,
    Aquamarine3,
    Aquamarine4,
    Azure,
    Azure1,
    Azure2,
    Azure3,
    Azure4,
    Beige,
    Bisque,
    Bisque1,
    Bisque2,
    Bisque3,
    Bisque4,
    Black,
    BlanchedAlmond,
    Blue,
    Blue1,
    Blue2,
    Blue3,
    Blue4,
    BlueViolet,
    Brown,
    Brown1,
    Brown2,
    Brown3,
    Brown4,
    BurlyWood,
    BurlyWood1,
    BurlyWood2,
    BurlyWood3,
    BurlyWood4,
    CadetBlue,
    CadetBlue1,
    CadetBlue2,
    CadetBlue3,
    CadetBlue4,
    ChartReuse,
    ChartReuse1,
    ChartReuse2,
    ChartReuse3,
    ChartReuse4,
    Chocolate,
    Chocolate1,
    Chocolate2,
    Chocolate3,
    Chocolate4,
    Coral,
    Coral1,
    Coral2,
    Coral3,
    Coral4,
    CornflowerBlue,
    CornSilk,
    CornSilk1,
    CornSilk2,
    CornSilk3,
    CornSilk4,
    Crimson,
    Cyan,
    Cyan1,
    Cyan2,
    Cyan3,
    Cyan4,
    DarkBlue,
    DarkCyan,
    DarkGoldenRod,
    DarkGoldenRod1,
    DarkGoldenRod2,
    DarkGoldenRod3,
    DarkGoldenRod4,
    DarkGray,
    DarkGreen,
    DarkGrey,
    DarkKhaki,
    DarkMagenta,
    DarkOliveGreen,
    DarkOliveGreen1,
    DarkOliveGreen2,
    DarkOliveGreen3,
    DarkOliveGreen4,
    DarkOrange,
    DarkOrange1,
    DarkOrange2,
    DarkOrange3,
    DarkOrange4,
    DarkOrchid,
    DarkOrchid1,
    DarkOrchid2,
    DarkOrchid3,
    DarkOrchid4,
    DarkRed,
    DarkSalmon,
    DarkSeaGreen,
    DarkSeaGreen1,
    DarkSeaGreen2,
    DarkSeaGreen3,
    DarkSeaGreen4,
    DarkSlateBlue,
    DarkSlateGray,
    DarkSlateGray1,
    DarkSlateGray2,
    DarkSlateGray3,
    DarkSlateGray4,
    DarkSlateGrey,
    DarkTurquoise,
    DarkViolet,
    DeepPink,
    DeepPink1,
    DeepPink2,
    DeepPink3,
    DeepPink4,
    DeepSkyBlue,
    DeepSkyBlue1,
    DeepSkyBlue2,
    DeepSkyBlue3,
    DeepSkyBlue4,
    DimGray,
    DimGrey,
    DodgerBlue,
    DodgerBlue1,
    DodgerBlue2,
    DodgerBlue3,
    DodgerBlue4,
    FireBrick,
    FireBrick1,
    FireBrick2,
    FireBrick3,
    FireBrick4,
    FloralWhite,
    ForestGreen,
    Fuchsia,
    Gainsboro,
    GhostWhite,
    Gold,
    Gold1,
    Gold2,
    Gold3,
    Gold4,
    GoldenRod,
    GoldenRod1,
    GoldenRod2,
    GoldenRod3,
    GoldenRod4,
    Gray,
    Gray0,
    Gray1,
    Gray2,
    Gray3,
    Gray4,
    Gray5,
    Gray6,
    Gray7,
    Gray8,
    Gray9,
    Gray10,
    Gray11,
    Gray12,
    Gray13,
    Gray14,
    Gray15,
    Gray16,
    Gray17,
    Gray18,
    Gray19,
    Gray20,
    Gray21,
    Gray22,
    Gray23,
    Gray24,
    Gray25,
    Gray26,
    Gray27,
    Gray28,
    Gray29,
    Gray30,
    Gray31,
    Gray32,
    Gray33,
    Gray34,
    Gray35,
    Gray36,
    Gray37,
    Gray38,
    Gray39,
    Gray40,
    Gray41,
    Gray42,
    Gray43,
    Gray44,
    Gray45,
    Gray46,
    Gray47,
    Gray48,
    Gray49,
    Gray50,
    Gray51,
    Gray52,
    Gray53,
    Gray54,
    Gray55,
    Gray56,
    Gray57,
    Gray58,
    Gray59,
    Gray60,
    Gray61,
    Gray62,
    Gray63,
    Gray64,
    Gray65,
    Gray66,
    Gray67,
    Gray68,
    Gray69,
    Gray70,
    Gray71,
    Gray72,
    Gray73,
    Gray74,
    Gray75,
    Gray76,
    Gray77,
    Gray78,
    Gray79,
    Gray80,
    Gray81,
    Gray82,
    Gray83,
    Gray84,
    Gray85,
    Gray86,
    Gray87,
    Gray88,
    Gray89,
    Gray90,
    Gray91,
    Gray92,
    Gray93,
    Gray94,
    Gray95,
    Gray96,
    Gray97,
    Gray98,
    Gray99,
    Gray100,
    Green,
    Green1,
    Green2,
    Green3,
    Green4,
    GreenYellow,
    Grey,
    Grey0,
    Grey1,
    Grey2,
    Grey3,
    Grey4,
    Grey5,
    Grey6,
    Grey7,
    Grey8,
    Grey9,
    Grey10,
    Grey11,
    Grey12,
    Grey13,
    Grey14,
    Grey15,
    Grey16,
    Grey17,
    Grey18,
    Grey19,
    Grey20,
    Grey21,
    Grey22,
    Grey23,
    Grey24,
    Grey25,
    Grey26,
    Grey27,
    Grey28,
    Grey29,
    Grey30,
    Grey31,
    Grey32,
    Grey33,
    Grey34,
    Grey35,
    Grey36,
    Grey37,
    Grey38,
    Grey39,
    Grey40,
    Grey41,
    Grey42,
    Grey43,
    Grey44,
    Grey45,
    Grey46,
    Grey47,
    Grey48,
    Grey49,
    Grey50,
    Grey51,
    Grey52,
    Grey53,
    Grey54,
    Grey55,
    Grey56,
    Grey57,
    Grey58,
    Grey59,
    Grey60,
    Grey61,
    Grey62,
    Grey63,
    Grey64,
    Grey65,
    Grey66,
    Grey67,
    Grey68,
    Grey69,
    Grey70,
    Grey71,
    Grey72,
    Grey73,
    Grey74,
    Grey75,
    Grey76,
    Grey77,
    Grey78,
    Grey79,
    Grey80,
    Grey81,
    Grey82,
    Grey83,
    Grey84,
    Grey85,
    Grey86,
    Grey87,
    Grey88,
    Grey89,
    Grey90,
    Grey91,
    Grey92,
    Grey93,
    Grey94,
    Grey95,
    Grey96,
    Grey97,
    Grey98,
    Grey99,
    Grey100,
    HoneyDew,
    HoneyDew1,
    HoneyDew2,
    HoneyDew3,
    HoneyDew4,
    HotPink,
    HotPink1,
    HotPink2,
    HotPink3,
    HotPink4,
    IndianRed,
    IndianRed1,
    IndianRed2,
    IndianRed3,
    IndianRed4,
    Indigo,
    Invis,
    Ivory,
    Ivory1,
    Ivory2,
    Ivory3,
    Ivory4,
    Khaki,
    Khaki1,
    Khaki2,
    Khaki3,
    Khaki4,
    Lavender,
    LavenderBlush,
    LavenderBlush1,
    LavenderBlush2,
    LavenderBlush3,
    LavenderBlush4,
    LawnGreen,
    LemonChiffon,
    LemonChiffon1,
    LemonChiffon2,
    LemonChiffon3,
    LemonChiffon4,
    LightBlue,
    LightBlue1,
    LightBlue2,
    LightBlue3,
    LightBlue4,
    LightCoral,
    LightCyan,
    LightCyan1,
    LightCyan2,
    LightCyan3,
    LightCyan4,
    LightGoldenRod,
    LightGoldenRod1,
    LightGoldenRod2,
    LightGoldenRod3,
    LightGoldenRod4,
    LightGoldenRodYellow,
    LightGray,
    LightGreen,
    LightGrey,
    LightPink,
    LightPink1,
    LightPink2,
    LightPink3,
    LightPink4,
    LightSalmon,
    LightSalmon1,
    LightSalmon2,
    LightSalmon3,
    LightSalmon4,
    LightSeaGreen,
    LightSkyBlue,
    LightSkyBlue1,
    LightSkyBlue2,
    LightSkyBlue3,
    LightSkyBlue4,
    LightSlateBlue,
    LightSlateGray,
    LightSlateGrey,
    LightSteelBlue,
    LightSteelBlue1,
    LightSteelBlue2,
    LightSteelBlue3,
    LightSteelBlue4,
    LightYellow,
    LightYellow1,
    LightYellow2,
    LightYellow3,
    LightYellow4,
    Lime,
    LimeGreen,
    Linen,
    Magenta,
    Magenta1,
    Magenta2,
    Magenta3,
    Magenta4,
    Maroon,
    Maroon1,
    Maroon2,
    Maroon3,
    Maroon4,
    MediumAquamarine,
    MediumBlue,
    MediumOrchid,
    MediumOrchid1,
    MediumOrchid2,
    MediumOrchid3,
    MediumOrchid4,
    MediumPurple,
    MediumPurple1,
    MediumPurple2,
    MediumPurple3,
    MediumPurple4,
    MediumSeaGreen,
    MediumSlateBlue,
    MediumSpringGreen,
    MediumTurquoise,
    MediumVioletRed,
    MidnightBlue,
    MintCream,
    MistyRose,
    MistyRose1,
    MistyRose2,
    MistyRose3,
    MistyRose4,
    Moccasin,
    NavajoWhite,
    NavajoWhite1,
    NavajoWhite2,
    NavajoWhite3,
    NavajoWhite4,
    Navy,
    NavyBlue,
    #[default]
    None,
    OldLace,
    Olive,
    OliveDrab,
    OliveDrab1,
    OliveDrab2,
    OliveDrab3,
    OliveDrab4,
    Orange,
    Orange1,
    Orange2,
    Orange3,
    Orange4,
    OrangeRed,
    OrangeRed1,
    OrangeRed2,
    OrangeRed3,
    OrangeRed4,
    Orchid,
    Orchid1,
    Orchid2,
    Orchid3,
    Orchid4,
    PaleGoldenRod,
    PaleGreen,
    PaleGreen1,
    PaleGreen2,
    PaleGreen3,
    PaleGreen4,
    PaleTurquoise,
    PaleTurquoise1,
    PaleTurquoise2,
    PaleTurquoise3,
    PaleTurquoise4,
    PaleVioletRed,
    PaleVioletRed1,
    PaleVioletRed2,
    PaleVioletRed3,
    PaleVioletRed4,
    PapayaWhip,
    PeachPuff,
    PeachPuff1,
    PeachPuff2,
    PeachPuff3,
    PeachPuff4,
    Peru,
    Pink,
    Pink1,
    Pink2,
    Pink3,
    Pink4,
    Plum,
    Plum1,
    Plum2,
    Plum3,
    Plum4,
    PowderBlue,
    Purple,
    Purple1,
    Purple2,
    Purple3,
    Purple4,
    RebeccaPurple,
    Red,
    Red1,
    Red2,
    Red3,
    Red4,
    RosyBrown,
    RosyBrown1,
    RosyBrown2,
    RosyBrown3,
    RosyBrown4,
    RoyalBlue,
    RoyalBlue1,
    RoyalBlue2,
    RoyalBlue3,
    RoyalBlue4,
    SaddleBrown,
    Salmon,
    Salmon1,
    Salmon2,
    Salmon3,
    Salmon4,
    SandyBrown,
    SeaGreen,
    SeaGreen1,
    SeaGreen2,
    SeaGreen3,
    SeaGreen4,
    SeaShell,
    SeaShell1,
    SeaShell2,
    SeaShell3,
    SeaShell4,
    Sienna,
    Sienna1,
    Sienna2,
    Sienna3,
    Sienna4,
    Silver,
    SkyBlue,
    SkyBlue1,
    SkyBlue2,
    SkyBlue3,
    SkyBlue4,
    SlateBlue,
    SlateBlue1,
    SlateBlue2,
    SlateBlue3,
    SlateBlue4,
    SlateGray,
    SlateGray1,
    SlateGray2,
    SlateGray3,
    SlateGray4,
    SlateGrey,
    Snow,
    Snow1,
    Snow2,
    Snow3,
    Snow4,
    SpringGreen,
    SpringGreen1,
    SpringGreen2,
    SpringGreen3,
    SpringGreen4,
    SteelBlue,
    SteelBlue1,
    SteelBlue2,
    SteelBlue3,
    SteelBlue4,
    Tan,
    Tan1,
    Tan2,
    Tan3,
    Tan4,
    Teal,
    Thistle,
    Thistle1,
    Thistle2,
    Thistle3,
    Thistle4,
    Tomato,
    Tomato1,
    Tomato2,
    Tomato3,
    Tomato4,
    Transparent,
    Turquoise,
    Turquoise1,
    Turquoise2,
    Turquoise3,
    Turquoise4,
    Violet,
    VioletRed,
    VioletRed1,
    VioletRed2,
    VioletRed3,
    VioletRed4,
    WebGray,
    WebGreen,
    WebGrey,
    WebMaroon,
    WebPurple,
    Wheat,
    Wheat1,
    Wheat2,
    Wheat3,
    Wheat4,
    White,
    WhiteSmoke,
    X11Gray,
    X11Green,
    X11Grey,
    X11Maroon,
    X11Purple,
    Yellow,
    Yellow1,
    Yellow2,
    Yellow3,
    Yellow4,
    YellowGreen,
}

impl Color {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::AliceBlue => "aliceblue",
            Self::AntiqueWhite => "antiquewhite",
            Self::AntiqueWhite1 => "antiquewhite1",
            Self::AntiqueWhite2 => "antiquewhite2",
            Self::AntiqueWhite3 => "antiquewhite3",
            Self::AntiqueWhite4 => "antiquewhite4",
            Self::Aqua => "aqua",
            Self::Aquamarine => "aquamarine",
            Self::Aquamarine1 => "aquamarine1",
            Self::Aquamarine2 => "aquamarine2",
            Self::Aquamarine3 => "aquamarine3",
            Self::Aquamarine4 => "aquamarine4",
            Self::Azure => "azure",
            Self::Azure1 => "azure1",
            Self::Azure2 => "azure2",
            Self::Azure3 => "azure3",
            Self::Azure4 => "azure4",
            Self::Beige => "beige",
            Self::Bisque => "bisque",
            Self::Bisque1 => "bisque1",
            Self::Bisque2 => "bisque2",
            Self::Bisque3 => "bisque3",
            Self::Bisque4 => "bisque4",
            Self::Black => "black",
            Self::BlanchedAlmond => "blanchedalmond",
            Self::Blue => "blue",
            Self::Blue1 => "blue1",
            Self::Blue2 => "blue2",
            Self::Blue3 => "blue3",
            Self::Blue4 => "blue4",
            Self::BlueViolet => "blueviolet",
            Self::Brown => "brown",
            Self::Brown1 => "brown1",
            Self::Brown2 => "brown2",
            Self::Brown3 => "brown3",
            Self::Brown4 => "brown4",
            Self::BurlyWood => "burlywood",
            Self::BurlyWood1 => "burlywood1",
            Self::BurlyWood2 => "burlywood2",
            Self::BurlyWood3 => "burlywood3",
            Self::BurlyWood4 => "burlywood4",
            Self::CadetBlue => "cadetblue",
            Self::CadetBlue1 => "cadetblue1",
            Self::CadetBlue2 => "cadetblue2",
            Self::CadetBlue3 => "cadetblue3",
            Self::CadetBlue4 => "cadetblue4",
            Self::ChartReuse => "chartreuse",
            Self::ChartReuse1 => "chartreuse1",
            Self::ChartReuse2 => "chartreuse2",
            Self::ChartReuse3 => "chartreuse3",
            Self::ChartReuse4 => "chartreuse4",
            Self::Chocolate => "chocolate",
            Self::Chocolate1 => "chocolate1",
            Self::Chocolate2 => "chocolate2",
            Self::Chocolate3 => "chocolate3",
            Self::Chocolate4 => "chocolate4",
            Self::Coral => "coral",
            Self::Coral1 => "coral1",
            Self::Coral2 => "coral2",
            Self::Coral3 => "coral3",
            Self::Coral4 => "coral4",
            Self::CornflowerBlue => "cornflowerblue",
            Self::CornSilk => "cornsilk",
            Self::CornSilk1 => "cornsilk1",
            Self::CornSilk2 => "cornsilk2",
            Self::CornSilk3 => "cornsilk3",
            Self::CornSilk4 => "cornsilk4",
            Self::Crimson => "crimson",
            Self::Cyan => "cyan",
            Self::Cyan1 => "cyan1",
            Self::Cyan2 => "cyan2",
            Self::Cyan3 => "cyan3",
            Self::Cyan4 => "cyan4",
            Self::DarkBlue => "darkblue",
            Self::DarkCyan => "darkcyan",
            Self::DarkGoldenRod => "darkgoldenrod",
            Self::DarkGoldenRod1 => "darkgoldenrod1",
            Self::DarkGoldenRod2 => "darkgoldenrod2",
            Self::DarkGoldenRod3 => "darkgoldenrod3",
            Self::DarkGoldenRod4 => "darkgoldenrod4",
            Self::DarkGray => "darkgray",
            Self::DarkGreen => "darkgreen",
            Self::DarkGrey => "darkgrey",
            Self::DarkKhaki => "darkkhaki",
            Self::DarkMagenta => "darkmagenta",
            Self::DarkOliveGreen => "darkolivegreen",
            Self::DarkOliveGreen1 => "darkolivegreen1",
            Self::DarkOliveGreen2 => "darkolivegreen2",
            Self::DarkOliveGreen3 => "darkolivegreen3",
            Self::DarkOliveGreen4 => "darkolivegreen4",
            Self::DarkOrange => "darkorange",
            Self::DarkOrange1 => "darkorange1",
            Self::DarkOrange2 => "darkorange2",
            Self::DarkOrange3 => "darkorange3",
            Self::DarkOrange4 => "darkorange4",
            Self::DarkOrchid => "darkorchid",
            Self::DarkOrchid1 => "darkorchid1",
            Self::DarkOrchid2 => "darkorchid2",
            Self::DarkOrchid3 => "darkorchid3",
            Self::DarkOrchid4 => "darkorchid4",
            Self::DarkRed => "darkred",
            Self::DarkSalmon => "darksalmon",
            Self::DarkSeaGreen => "darkseagreen",
            Self::DarkSeaGreen1 => "darkseagreen1",
            Self::DarkSeaGreen2 => "darkseagreen2",
            Self::DarkSeaGreen3 => "darkseagreen3",
            Self::DarkSeaGreen4 => "darkseagreen4",
            Self::DarkSlateBlue => "darkslateblue",
            Self::DarkSlateGray => "darkslategray",
            Self::DarkSlateGray1 => "darkslategray1",
            Self::DarkSlateGray2 => "darkslategray2",
            Self::DarkSlateGray3 => "darkslategray3",
            Self::DarkSlateGray4 => "darkslategray4",
            Self::DarkSlateGrey => "darkslategrey",
            Self::DarkTurquoise => "darkturquoise",
            Self::DarkViolet => "darkviolet",
            Self::DeepPink => "deeppink",
            Self::DeepPink1 => "deeppink1",
            Self::DeepPink2 => "deeppink2",
            Self::DeepPink3 => "deeppink3",
            Self::DeepPink4 => "deeppink4",
            Self::DeepSkyBlue => "deepskyblue",
            Self::DeepSkyBlue1 => "deepskyblue1",
            Self::DeepSkyBlue2 => "deepskyblue2",
            Self::DeepSkyBlue3 => "deepskyblue3",
            Self::DeepSkyBlue4 => "deepskyblue4",
            Self::DimGray => "dimgray",
            Self::DimGrey => "dimgrey",
            Self::DodgerBlue => "dodgerblue",
            Self::DodgerBlue1 => "dodgerblue1",
            Self::DodgerBlue2 => "dodgerblue2",
            Self::DodgerBlue3 => "dodgerblue3",
            Self::DodgerBlue4 => "dodgerblue4",
            Self::FireBrick => "firebrick",
            Self::FireBrick1 => "firebrick1",
            Self::FireBrick2 => "firebrick2",
            Self::FireBrick3 => "firebrick3",
            Self::FireBrick4 => "firebrick4",
            Self::FloralWhite => "floralwhite",
            Self::ForestGreen => "forestgreen",
            Self::Fuchsia => "fuchsia",
            Self::Gainsboro => "gainsboro",
            Self::GhostWhite => "ghostwhite",
            Self::Gold => "gold",
            Self::Gold1 => "gold1",
            Self::Gold2 => "gold2",
            Self::Gold3 => "gold3",
            Self::Gold4 => "gold4",
            Self::GoldenRod => "goldenrod",
            Self::GoldenRod1 => "goldenrod1",
            Self::GoldenRod2 => "goldenrod2",
            Self::GoldenRod3 => "goldenrod3",
            Self::GoldenRod4 => "goldenrod4",
            Self::Gray => "gray",
            Self::Gray0 => "gray0",
            Self::Gray1 => "gray1",
            Self::Gray2 => "gray2",
            Self::Gray3 => "gray3",
            Self::Gray4 => "gray4",
            Self::Gray5 => "gray5",
            Self::Gray6 => "gray6",
            Self::Gray7 => "gray7",
            Self::Gray8 => "gray8",
            Self::Gray9 => "gray9",
            Self::Gray10 => "gray10",
            Self::Gray11 => "gray11",
            Self::Gray12 => "gray12",
            Self::Gray13 => "gray13",
            Self::Gray14 => "gray14",
            Self::Gray15 => "gray15",
            Self::Gray16 => "gray16",
            Self::Gray17 => "gray17",
            Self::Gray18 => "gray18",
            Self::Gray19 => "gray19",
            Self::Gray20 => "gray20",
            Self::Gray21 => "gray21",
            Self::Gray22 => "gray22",
            Self::Gray23 => "gray23",
            Self::Gray24 => "gray24",
            Self::Gray25 => "gray25",
            Self::Gray26 => "gray26",
            Self::Gray27 => "gray27",
            Self::Gray28 => "gray28",
            Self::Gray29 => "gray29",
            Self::Gray30 => "gray30",
            Self::Gray31 => "gray31",
            Self::Gray32 => "gray32",
            Self::Gray33 => "gray33",
            Self::Gray34 => "gray34",
            Self::Gray35 => "gray35",
            Self::Gray36 => "gray36",
            Self::Gray37 => "gray37",
            Self::Gray38 => "gray38",
            Self::Gray39 => "gray39",
            Self::Gray40 => "gray40",
            Self::Gray41 => "gray41",
            Self::Gray42 => "gray42",
            Self::Gray43 => "gray43",
            Self::Gray44 => "gray44",
            Self::Gray45 => "gray45",
            Self::Gray46 => "gray46",
            Self::Gray47 => "gray47",
            Self::Gray48 => "gray48",
            Self::Gray49 => "gray49",
            Self::Gray50 => "gray50",
            Self::Gray51 => "gray51",
            Self::Gray52 => "gray52",
            Self::Gray53 => "gray53",
            Self::Gray54 => "gray54",
            Self::Gray55 => "gray55",
            Self::Gray56 => "gray56",
            Self::Gray57 => "gray57",
            Self::Gray58 => "gray58",
            Self::Gray59 => "gray59",
            Self::Gray60 => "gray60",
            Self::Gray61 => "gray61",
            Self::Gray62 => "gray62",
            Self::Gray63 => "gray63",
            Self::Gray64 => "gray64",
            Self::Gray65 => "gray65",
            Self::Gray66 => "gray66",
            Self::Gray67 => "gray67",
            Self::Gray68 => "gray68",
            Self::Gray69 => "gray69",
            Self::Gray70 => "gray70",
            Self::Gray71 => "gray71",
            Self::Gray72 => "gray72",
            Self::Gray73 => "gray73",
            Self::Gray74 => "gray74",
            Self::Gray75 => "gray75",
            Self::Gray76 => "gray76",
            Self::Gray77 => "gray77",
            Self::Gray78 => "gray78",
            Self::Gray79 => "gray79",
            Self::Gray80 => "gray80",
            Self::Gray81 => "gray81",
            Self::Gray82 => "gray82",
            Self::Gray83 => "gray83",
            Self::Gray84 => "gray84",
            Self::Gray85 => "gray85",
            Self::Gray86 => "gray86",
            Self::Gray87 => "gray87",
            Self::Gray88 => "gray88",
            Self::Gray89 => "gray89",
            Self::Gray90 => "gray90",
            Self::Gray91 => "gray91",
            Self::Gray92 => "gray92",
            Self::Gray93 => "gray93",
            Self::Gray94 => "gray94",
            Self::Gray95 => "gray95",
            Self::Gray96 => "gray96",
            Self::Gray97 => "gray97",
            Self::Gray98 => "gray98",
            Self::Gray99 => "gray99",
            Self::Gray100 => "gray100",
            Self::Green => "green",
            Self::Green1 => "green1",
            Self::Green2 => "green2",
            Self::Green3 => "green3",
            Self::Green4 => "green4",
            Self::GreenYellow => "greenyellow",
            Self::Grey => "grey",
            Self::Grey0 => "grey0",
            Self::Grey1 => "grey1",
            Self::Grey2 => "grey2",
            Self::Grey3 => "grey3",
            Self::Grey4 => "grey4",
            Self::Grey5 => "grey5",
            Self::Grey6 => "grey6",
            Self::Grey7 => "grey7",
            Self::Grey8 => "grey8",
            Self::Grey9 => "grey9",
            Self::Grey10 => "grey10",
            Self::Grey11 => "grey11",
            Self::Grey12 => "grey12",
            Self::Grey13 => "grey13",
            Self::Grey14 => "grey14",
            Self::Grey15 => "grey15",
            Self::Grey16 => "grey16",
            Self::Grey17 => "grey17",
            Self::Grey18 => "grey18",
            Self::Grey19 => "grey19",
            Self::Grey20 => "grey20",
            Self::Grey21 => "grey21",
            Self::Grey22 => "grey22",
            Self::Grey23 => "grey23",
            Self::Grey24 => "grey24",
            Self::Grey25 => "grey25",
            Self::Grey26 => "grey26",
            Self::Grey27 => "grey27",
            Self::Grey28 => "grey28",
            Self::Grey29 => "grey29",
            Self::Grey30 => "grey30",
            Self::Grey31 => "grey31",
            Self::Grey32 => "grey32",
            Self::Grey33 => "grey33",
            Self::Grey34 => "grey34",
            Self::Grey35 => "grey35",
            Self::Grey36 => "grey36",
            Self::Grey37 => "grey37",
            Self::Grey38 => "grey38",
            Self::Grey39 => "grey39",
            Self::Grey40 => "grey40",
            Self::Grey41 => "grey41",
            Self::Grey42 => "grey42",
            Self::Grey43 => "grey43",
            Self::Grey44 => "grey44",
            Self::Grey45 => "grey45",
            Self::Grey46 => "grey46",
            Self::Grey47 => "grey47",
            Self::Grey48 => "grey48",
            Self::Grey49 => "grey49",
            Self::Grey50 => "grey50",
            Self::Grey51 => "grey51",
            Self::Grey52 => "grey52",
            Self::Grey53 => "grey53",
            Self::Grey54 => "grey54",
            Self::Grey55 => "grey55",
            Self::Grey56 => "grey56",
            Self::Grey57 => "grey57",
            Self::Grey58 => "grey58",
            Self::Grey59 => "grey59",
            Self::Grey60 => "grey60",
            Self::Grey61 => "grey61",
            Self::Grey62 => "grey62",
            Self::Grey63 => "grey63",
            Self::Grey64 => "grey64",
            Self::Grey65 => "grey65",
            Self::Grey66 => "grey66",
            Self::Grey67 => "grey67",
            Self::Grey68 => "grey68",
            Self::Grey69 => "grey69",
            Self::Grey70 => "grey70",
            Self::Grey71 => "grey71",
            Self::Grey72 => "grey72",
            Self::Grey73 => "grey73",
            Self::Grey74 => "grey74",
            Self::Grey75 => "grey75",
            Self::Grey76 => "grey76",
            Self::Grey77 => "grey77",
            Self::Grey78 => "grey78",
            Self::Grey79 => "grey79",
            Self::Grey80 => "grey80",
            Self::Grey81 => "grey81",
            Self::Grey82 => "grey82",
            Self::Grey83 => "grey83",
            Self::Grey84 => "grey84",
            Self::Grey85 => "grey85",
            Self::Grey86 => "grey86",
            Self::Grey87 => "grey87",
            Self::Grey88 => "grey88",
            Self::Grey89 => "grey89",
            Self::Grey90 => "grey90",
            Self::Grey91 => "grey91",
            Self::Grey92 => "grey92",
            Self::Grey93 => "grey93",
            Self::Grey94 => "grey94",
            Self::Grey95 => "grey95",
            Self::Grey96 => "grey96",
            Self::Grey97 => "grey97",
            Self::Grey98 => "grey98",
            Self::Grey99 => "grey99",
            Self::Grey100 => "grey100",
            Self::HoneyDew => "honeydew",
            Self::HoneyDew1 => "honeydew1",
            Self::HoneyDew2 => "honeydew2",
            Self::HoneyDew3 => "honeydew3",
            Self::HoneyDew4 => "honeydew4",
            Self::HotPink => "hotpink",
            Self::HotPink1 => "hotpink1",
            Self::HotPink2 => "hotpink2",
            Self::HotPink3 => "hotpink3",
            Self::HotPink4 => "hotpink4",
            Self::IndianRed => "indianred",
            Self::IndianRed1 => "indianred1",
            Self::IndianRed2 => "indianred2",
            Self::IndianRed3 => "indianred3",
            Self::IndianRed4 => "indianred4",
            Self::Indigo => "indigo",
            Self::Invis => "invis",
            Self::Ivory => "ivory",
            Self::Ivory1 => "ivory1",
            Self::Ivory2 => "ivory2",
            Self::Ivory3 => "ivory3",
            Self::Ivory4 => "ivory4",
            Self::Khaki => "khaki",
            Self::Khaki1 => "khaki1",
            Self::Khaki2 => "khaki2",
            Self::Khaki3 => "khaki3",
            Self::Khaki4 => "khaki4",
            Self::Lavender => "lavender",
            Self::LavenderBlush => "lavenderblush",
            Self::LavenderBlush1 => "lavenderblush1",
            Self::LavenderBlush2 => "lavenderblush2",
            Self::LavenderBlush3 => "lavenderblush3",
            Self::LavenderBlush4 => "lavenderblush4",
            Self::LawnGreen => "lawngreen",
            Self::LemonChiffon => "lemonchiffon",
            Self::LemonChiffon1 => "lemonchiffon1",
            Self::LemonChiffon2 => "lemonchiffon2",
            Self::LemonChiffon3 => "lemonchiffon3",
            Self::LemonChiffon4 => "lemonchiffon4",
            Self::LightBlue => "lightblue",
            Self::LightBlue1 => "lightblue1",
            Self::LightBlue2 => "lightblue2",
            Self::LightBlue3 => "lightblue3",
            Self::LightBlue4 => "lightblue4",
            Self::LightCoral => "lightcoral",
            Self::LightCyan => "lightcyan",
            Self::LightCyan1 => "lightcyan1",
            Self::LightCyan2 => "lightcyan2",
            Self::LightCyan3 => "lightcyan3",
            Self::LightCyan4 => "lightcyan4",
            Self::LightGoldenRod => "lightgoldenrod",
            Self::LightGoldenRod1 => "lightgoldenrod1",
            Self::LightGoldenRod2 => "lightgoldenrod2",
            Self::LightGoldenRod3 => "lightgoldenrod3",
            Self::LightGoldenRod4 => "lightgoldenrod4",
            Self::LightGoldenRodYellow => "lightgoldenrodyellow",
            Self::LightGray => "lightgray",
            Self::LightGreen => "lightgreen",
            Self::LightGrey => "lightgrey",
            Self::LightPink => "lightpink",
            Self::LightPink1 => "lightpink1",
            Self::LightPink2 => "lightpink2",
            Self::LightPink3 => "lightpink3",
            Self::LightPink4 => "lightpink4",
            Self::LightSalmon => "lightsalmon",
            Self::LightSalmon1 => "lightsalmon1",
            Self::LightSalmon2 => "lightsalmon2",
            Self::LightSalmon3 => "lightsalmon3",
            Self::LightSalmon4 => "lightsalmon4",
            Self::LightSeaGreen => "lightseagreen",
            Self::LightSkyBlue => "lightskyblue",
            Self::LightSkyBlue1 => "lightskyblue1",
            Self::LightSkyBlue2 => "lightskyblue2",
            Self::LightSkyBlue3 => "lightskyblue3",
            Self::LightSkyBlue4 => "lightskyblue4",
            Self::LightSlateBlue => "lightslateblue",
            Self::LightSlateGray => "lightslategray",
            Self::LightSlateGrey => "lightslategrey",
            Self::LightSteelBlue => "lightsteelblue",
            Self::LightSteelBlue1 => "lightsteelblue1",
            Self::LightSteelBlue2 => "lightsteelblue2",
            Self::LightSteelBlue3 => "lightsteelblue3",
            Self::LightSteelBlue4 => "lightsteelblue4",
            Self::LightYellow => "lightyellow",
            Self::LightYellow1 => "lightyellow1",
            Self::LightYellow2 => "lightyellow2",
            Self::LightYellow3 => "lightyellow3",
            Self::LightYellow4 => "lightyellow4",
            Self::Lime => "lime",
            Self::LimeGreen => "limegreen",
            Self::Linen => "linen",
            Self::Magenta => "magenta",
            Self::Magenta1 => "magenta1",
            Self::Magenta2 => "magenta2",
            Self::Magenta3 => "magenta3",
            Self::Magenta4 => "magenta4",
            Self::Maroon => "maroon",
            Self::Maroon1 => "maroon1",
            Self::Maroon2 => "maroon2",
            Self::Maroon3 => "maroon3",
            Self::Maroon4 => "maroon4",
            Self::MediumAquamarine => "mediumaquamarine",
            Self::MediumBlue => "mediumblue",
            Self::MediumOrchid => "mediumorchid",
            Self::MediumOrchid1 => "mediumorchid1",
            Self::MediumOrchid2 => "mediumorchid2",
            Self::MediumOrchid3 => "mediumorchid3",
            Self::MediumOrchid4 => "mediumorchid4",
            Self::MediumPurple => "mediumpurple",
            Self::MediumPurple1 => "mediumpurple1",
            Self::MediumPurple2 => "mediumpurple2",
            Self::MediumPurple3 => "mediumpurple3",
            Self::MediumPurple4 => "mediumpurple4",
            Self::MediumSeaGreen => "mediumseagreen",
            Self::MediumSlateBlue => "mediumslateblue",
            Self::MediumSpringGreen => "mediumspringgreen",
            Self::MediumTurquoise => "mediumturquoise",
            Self::MediumVioletRed => "mediumvioletred",
            Self::MidnightBlue => "midnightblue",
            Self::MintCream => "mintcream",
            Self::MistyRose => "mistyrose",
            Self::MistyRose1 => "mistyrose1",
            Self::MistyRose2 => "mistyrose2",
            Self::MistyRose3 => "mistyrose3",
            Self::MistyRose4 => "mistyrose4",
            Self::Moccasin => "moccasin",
            Self::NavajoWhite => "navajowhite",
            Self::NavajoWhite1 => "navajowhite1",
            Self::NavajoWhite2 => "navajowhite2",
            Self::NavajoWhite3 => "navajowhite3",
            Self::NavajoWhite4 => "navajowhite4",
            Self::Navy => "navy",
            Self::NavyBlue => "navyblue",
            Self::None => "none",
            Self::OldLace => "oldlace",
            Self::Olive => "olive",
            Self::OliveDrab => "olivedrab",
            Self::OliveDrab1 => "olivedrab1",
            Self::OliveDrab2 => "olivedrab2",
            Self::OliveDrab3 => "olivedrab3",
            Self::OliveDrab4 => "olivedrab4",
            Self::Orange => "orange",
            Self::Orange1 => "orange1",
            Self::Orange2 => "orange2",
            Self::Orange3 => "orange3",
            Self::Orange4 => "orange4",
            Self::OrangeRed => "orangered",
            Self::OrangeRed1 => "orangered1",
            Self::OrangeRed2 => "orangered2",
            Self::OrangeRed3 => "orangered3",
            Self::OrangeRed4 => "orangered4",
            Self::Orchid => "orchid",
            Self::Orchid1 => "orchid1",
            Self::Orchid2 => "orchid2",
            Self::Orchid3 => "orchid3",
            Self::Orchid4 => "orchid4",
            Self::PaleGoldenRod => "palegoldenrod",
            Self::PaleGreen => "palegreen",
            Self::PaleGreen1 => "palegreen1",
            Self::PaleGreen2 => "palegreen2",
            Self::PaleGreen3 => "palegreen3",
            Self::PaleGreen4 => "palegreen4",
            Self::PaleTurquoise => "paleturquoise",
            Self::PaleTurquoise1 => "paleturquoise1",
            Self::PaleTurquoise2 => "paleturquoise2",
            Self::PaleTurquoise3 => "paleturquoise3",
            Self::PaleTurquoise4 => "paleturquoise4",
            Self::PaleVioletRed => "palevioletred",
            Self::PaleVioletRed1 => "palevioletred1",
            Self::PaleVioletRed2 => "palevioletred2",
            Self::PaleVioletRed3 => "palevioletred3",
            Self::PaleVioletRed4 => "palevioletred4",
            Self::PapayaWhip => "papayawhip",
            Self::PeachPuff => "peachpuff",
            Self::PeachPuff1 => "peachpuff1",
            Self::PeachPuff2 => "peachpuff2",
            Self::PeachPuff3 => "peachpuff3",
            Self::PeachPuff4 => "peachpuff4",
            Self::Peru => "peru",
            Self::Pink => "pink",
            Self::Pink1 => "pink1",
            Self::Pink2 => "pink2",
            Self::Pink3 => "pink3",
            Self::Pink4 => "pink4",
            Self::Plum => "plum",
            Self::Plum1 => "plum1",
            Self::Plum2 => "plum2",
            Self::Plum3 => "plum3",
            Self::Plum4 => "plum4",
            Self::PowderBlue => "powderblue",
            Self::Purple => "purple",
            Self::Purple1 => "purple1",
            Self::Purple2 => "purple2",
            Self::Purple3 => "purple3",
            Self::Purple4 => "purple4",
            Self::RebeccaPurple => "rebeccapurple",
            Self::Red => "red",
            Self::Red1 => "red1",
            Self::Red2 => "red2",
            Self::Red3 => "red3",
            Self::Red4 => "red4",
            Self::RosyBrown => "rosybrown",
            Self::RosyBrown1 => "rosybrown1",
            Self::RosyBrown2 => "rosybrown2",
            Self::RosyBrown3 => "rosybrown3",
            Self::RosyBrown4 => "rosybrown4",
            Self::RoyalBlue => "royalblue",
            Self::RoyalBlue1 => "royalblue1",
            Self::RoyalBlue2 => "royalblue2",
            Self::RoyalBlue3 => "royalblue3",
            Self::RoyalBlue4 => "royalblue4",
            Self::SaddleBrown => "saddlebrown",
            Self::Salmon => "salmon",
            Self::Salmon1 => "salmon1",
            Self::Salmon2 => "salmon2",
            Self::Salmon3 => "salmon3",
            Self::Salmon4 => "salmon4",
            Self::SandyBrown => "sandybrown",
            Self::SeaGreen => "seagreen",
            Self::SeaGreen1 => "seagreen1",
            Self::SeaGreen2 => "seagreen2",
            Self::SeaGreen3 => "seagreen3",
            Self::SeaGreen4 => "seagreen4",
            Self::SeaShell => "seashell",
            Self::SeaShell1 => "seashell1",
            Self::SeaShell2 => "seashell2",
            Self::SeaShell3 => "seashell3",
            Self::SeaShell4 => "seashell4",
            Self::Sienna => "sienna",
            Self::Sienna1 => "sienna1",
            Self::Sienna2 => "sienna2",
            Self::Sienna3 => "sienna3",
            Self::Sienna4 => "sienna4",
            Self::Silver => "silver",
            Self::SkyBlue => "skyblue",
            Self::SkyBlue1 => "skyblue1",
            Self::SkyBlue2 => "skyblue2",
            Self::SkyBlue3 => "skyblue3",
            Self::SkyBlue4 => "skyblue4",
            Self::SlateBlue => "slateblue",
            Self::SlateBlue1 => "slateblue1",
            Self::SlateBlue2 => "slateblue2",
            Self::SlateBlue3 => "slateblue3",
            Self::SlateBlue4 => "slateblue4",
            Self::SlateGray => "slategray",
            Self::SlateGray1 => "slategray1",
            Self::SlateGray2 => "slategray2",
            Self::SlateGray3 => "slategray3",
            Self::SlateGray4 => "slategray4",
            Self::SlateGrey => "slategrey",
            Self::Snow => "snow",
            Self::Snow1 => "snow1",
            Self::Snow2 => "snow2",
            Self::Snow3 => "snow3",
            Self::Snow4 => "snow4",
            Self::SpringGreen => "springgreen",
            Self::SpringGreen1 => "springgreen1",
            Self::SpringGreen2 => "springgreen2",
            Self::SpringGreen3 => "springgreen3",
            Self::SpringGreen4 => "springgreen4",
            Self::SteelBlue => "steelblue",
            Self::SteelBlue1 => "steelblue1",
            Self::SteelBlue2 => "steelblue2",
            Self::SteelBlue3 => "steelblue3",
            Self::SteelBlue4 => "steelblue4",
            Self::Tan => "tan",
            Self::Tan1 => "tan1",
            Self::Tan2 => "tan2",
            Self::Tan3 => "tan3",
            Self::Tan4 => "tan4",
            Self::Teal => "teal",
            Self::Thistle => "thistle",
            Self::Thistle1 => "thistle1",
            Self::Thistle2 => "thistle2",
            Self::Thistle3 => "thistle3",
            Self::Thistle4 => "thistle4",
            Self::Tomato => "tomato",
            Self::Tomato1 => "tomato1",
            Self::Tomato2 => "tomato2",
            Self::Tomato3 => "tomato3",
            Self::Tomato4 => "tomato4",
            Self::Transparent => "transparent",
            Self::Turquoise => "turquoise",
            Self::Turquoise1 => "turquoise1",
            Self::Turquoise2 => "turquoise2",
            Self::Turquoise3 => "turquoise3",
            Self::Turquoise4 => "turquoise4",
            Self::Violet => "violet",
            Self::VioletRed => "violetred",
            Self::VioletRed1 => "violetred1",
            Self::VioletRed2 => "violetred2",
            Self::VioletRed3 => "violetred3",
            Self::VioletRed4 => "violetred4",
            Self::WebGray => "webgray",
            Self::WebGreen => "webgreen",
            Self::WebGrey => "webgrey",
            Self::WebMaroon => "webmaroon",
            Self::WebPurple => "webpurple",
            Self::Wheat => "wheat",
            Self::Wheat1 => "wheat1",
            Self::Wheat2 => "wheat2",
            Self::Wheat3 => "wheat3",
            Self::Wheat4 => "wheat4",
            Self::White => "white",
            Self::WhiteSmoke => "whitesmoke",
            Self::X11Gray => "x11gray",
            Self::X11Green => "x11green",
            Self::X11Grey => "x11grey",
            Self::X11Maroon => "x11maroon",
            Self::X11Purple => "x11purple",
            Self::Yellow => "yellow",
            Self::Yellow1 => "yellow1",
            Self::Yellow2 => "yellow2",
            Self::Yellow3 => "yellow3",
            Self::Yellow4 => "yellow4",
            Self::YellowGreen => "yellowgreen",
        }
    }
}
